import xgboost as xgb
import m2cgen as m2c
import time
import re

print("\n--- PHASE 4: BRAIN EXTRACTION (VANILLA DOWNGRADE EDITION) ---")
start_time = time.time()

print(" -> Loading DOWNGRADED AI Brain from JSON...")
model = xgb.XGBClassifier()
model.load_model("branch_predictor_brain_DOWNGRADED.json")

# Prevents m2cgen from tripping over missing base_score metadata
model.base_score = 0.5 

print(" -> Transpiling to bare-metal C/C++...")
raw_c_code = m2c.export_to_c(model)

print(" -> Patching strict C++ memory violations...")
cpp_code = raw_c_code.replace("void score(double * input, double * output)", "inline void _m2cgen_score(double * input, double * output)")

cpp_code = re.sub(
    r"memcpy\(output, \(double\[\]\)\{(.*?), (.*?)\}, 2 \* sizeof\(double\)\);", 
    r"output[0] = \1;\n    output[1] = \2;", 
    cpp_code
)

print(" -> Building the Architectural Wrapper...")
header_content = f"""// AUTO-GENERATED BY XGBOOST TRANSPILER & M2CGEN
// ==================================================
// DO NOT EDIT MANUALLY - VANILLA DOWNGRADED PREDICTOR
// ==================================================
#ifndef AI_PREDICTOR_VANILLA_H
#define AI_PREDICTOR_VANILLA_H

#include <cstdint>

namespace AIPredictorVanilla {{

    // --- Raw Transpiled Decision Trees ---
{cpp_code}

    // --- The Clean Architectural Wrapper ---
    inline int predict(uint64_t pc, uint64_t target, int isBackward, uint8_t localHistory) {{
        
        double input[4] = {{ 
            static_cast<double>(pc), 
            static_cast<double>(target), 
            static_cast<double>(isBackward), 
            static_cast<double>(localHistory) 
        }};
        
        double output[2] = {{0.0, 0.0}};
        
        _m2cgen_score(input, output);
        
        return (output[1] > output[0]) ? 1 : 0;
    }}

}} // namespace AIPredictorVanilla

#endif // AI_PREDICTOR_VANILLA_H
"""

print(" -> Writing ai_predictor_VANILLA.h...")
with open("ai_predictor_VANILLA.h", "w") as f:
    f.write(header_content)

print(f" -> Execution Time: {time.time() - start_time:.2f} seconds")
print("\n==========================================")
print("      VANILLA EXTRACTION SUCCESSFUL!      ")
print("==========================================\n")